spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://configserver:8888
    bootstrap:
      enabled: true
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - TokenRelay=
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:9001" #Allow the origin of your request
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: admin-api
          uri: lb://litemall-admin-api
          predicates:
            - Path=/admin/**
        - id: wx-api
          uri: lb://litemall-wx-api
          predicates:
            - Path=/wx/**

server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

